on: [push, pull_request]

jobs:
  test:

    runs-on: macos-latest
#     strategy:
#       matrix:
#         os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install platformio
#     - name: Set up GCC
#       run: |
#         /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
#         brew install gcc
    - name: Run tests on the test_circular_buffer platform
      run: platformio test -e test_circular_buffer
